export default [
  {
    name: "Puerto Rico",
    regionCodes: ["PR"],
    species: [
      { code: "yesbla1" },
      { code: "elwwar1" },
      { code: "adewar1" },
      { code: "greman1" },
      { code: "anteup3" },
      { code: "purnig1" },
      { code: "antman3" },
      { code: "purbul1" },
      { code: "purvir1" },
      { code: "purpar1" },
      { code: "purtan1" },
      { code: "purtod1" },
      { code: "purlic1" },
      { code: "purfly1", isNear: true, notes: "Found in low numbers in Virgin Islands" },
      { code: "graori4" },
      { code: "purwoo1" },
      { code: "prsowl" },
      { code: "purspi" },
      { code: "pureme1" },
    ],
  },
  {
    name: "Grenada",
    regionCodes: ["GD"],
    species: [{ code: "gredov1" }, { code: "houwre11" }],
  },
  {
    name: "Saint Vincent",
    regionCodes: ["VC"],
    species: [{ code: "stvpar1" }, { code: "houwre10" }, { code: "whiwar1" }],
  },
  {
    name: "Guadeloupe",
    regionCodes: ["GP"],
    species: [{ code: "guawoo1" }],
  },
  {
    name: "Dominica",
    regionCodes: ["DM"],
    species: [{ code: "imppar1" }, { code: "renpar1" }],
  },
  {
    name: "Martinique",
    regionCodes: ["MQ"],
    species: [{ code: "whbthr3" }, { code: "marori1" }],
  },
  {
    name: "Saint Lucia",
    regionCodes: ["LC"],
    species: [{ code: "stlwar" }, { code: "slbfin1" }, { code: "stlori1" }, { code: "stlpar1" }, { code: "houwre8" }, { code: "whbthr4" }],
  },
  {
    name: "Barbados",
    regionCodes: ["BB"],
    species: [{ code: "barbul1" }],
  },
];